apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q1pr28fux-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q1pr28fux-go 
  name: q1pr28fux-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q1pr28fux-go 
